language: bash
sudo: required
services:
  - docker
script:
  - VERSION=$(cat VERSION)
  - REPO=greensheep/plex-server-docker-rpi
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t $REPO:$VERSION -t $REPO:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO:$VERSION
  - docker push $REPO:latest
