version: "3"
services:
  plex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plex
    network_mode: "host"
    ports:
      - 32400:32400
    restart: always
    volumes:
      - /home/alarm/media/plex/config:/config
      - /home/alarm/media/plex/data:/data
